sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t yibin7/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yibin7/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-1'
  app: 'docker'
  env: 'docker-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-1-296025538260'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

