sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t yibin7/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yibin7/docker-react npm run test -- --coverage

